# Generated by Django 4.1.5 on 2023-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_descroption_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='React_JS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Html_CSS',
        ),
    ]
