# Generated by Django 4.1.5 on 2023-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_react_js_rename_project_html_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolio/images/stack')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
