# Generated by Django 4.1.5 on 2023-11-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='img',
            new_name='image',
        ),
    ]
