# Generated by Django 4.1.5 on 2023-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_img_stack_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='portfolio/images/technologies')),
            ],
        ),
        migrations.AlterField(
            model_name='stack',
            name='image',
            field=models.FileField(upload_to='portfolio/images/stack'),
        ),
    ]
