# Generated by Django 4.1.5 on 2023-11-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_alter_stack_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Techo',
        ),
    ]
