# Generated by Django 4.1.5 on 2023-11-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_project_techo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Techo',
        ),
        migrations.AlterField(
            model_name='react_js',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/projects'),
        ),
    ]
