# Generated by Django 4.1.5 on 2023-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_delete_techo_alter_react_js_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='html_css',
            old_name='url',
            new_name='url_repos',
        ),
        migrations.RenameField(
            model_name='react_js',
            old_name='url',
            new_name='url_repos',
        ),
        migrations.AddField(
            model_name='html_css',
            name='url_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='react_js',
            name='url_site',
            field=models.URLField(blank=True),
        ),
    ]
