# Generated by Django 4.1.5 on 2024-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_rename_url_html_css_url_repos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Python_DJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="portfolio/images/projects")),
                ("url_site", models.URLField()),
                ("url_repos", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="react_js",
            name="url_repos",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="react_js",
            name="url_site",
            field=models.URLField(),
        ),
    ]
